import { execFileSync } from 'node:child_process';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

const REPO = join(import.meta.dirname, '..');

/**
 * Ask git whether a path is ignored.
 *
 * Delegating to `git check-ignore` rather than reimplementing gitignore
 * semantics in the test: a hand-rolled matcher was both incomplete and
 * prone to false positives, and the real answer is what matters here.
 */
function isIgnored(path: string): boolean {
  try {
    execFileSync('git', ['check-ignore', '--quiet', '--no-index', path], {
      cwd: REPO,
      stdio: 'ignore',
    });
    return true;
  } catch {
    // Exit code 1 means "not ignored"; anything else is also not ignored.
    return false;
  }
}

describe('gitignore', () => {
  it('ignores installed dependencies', () => {
    expect(isIgnored('node_modules/')).toBe(true);
  });

  it('ignores compiled output at any depth', () => {
    expect(isIgnored('packages/core/dist/')).toBe(true);
    expect(isIgnored('apps/desktop/dist/')).toBe(true);
    expect(isIgnored('apps/vscode-extension/dist/')).toBe(true);
  });

  it('ignores the bundled renderer', () => {
    // The bundle is generated by esbuild; committing it hides staleness.
    expect(isIgnored('apps/desktop/renderer/renderer.js')).toBe(true);
  });

  it('ignores packaged installers', () => {
    expect(isIgnored('apps/desktop/release/')).toBe(true);
    expect(isIgnored('apps/vscode-extension/waypoint-0.2.0.vsix')).toBe(true);
  });

  it('ignores the generated Android project', () => {
    expect(isIgnored('apps/desktop/android/')).toBe(true);
  });

  it('ignores runtime artifacts', () => {
    expect(isIgnored('learned_model.json')).toBe(true);
    expect(isIgnored('feedback.jsonl')).toBe(true);
    expect(isIgnored('dashboard.html')).toBe(true);
  });

  it('ignores coverage output', () => {
    expect(isIgnored('coverage.xml')).toBe(true);
    expect(isIgnored('htmlcov/')).toBe(true);
  });

  it('still tracks renderer source', () => {
    expect(isIgnored('apps/desktop/renderer/index.html')).toBe(false);
    expect(isIgnored('apps/desktop/renderer/styles.css')).toBe(false);
    expect(isIgnored('apps/desktop/src/renderer.ts')).toBe(false);
  });

  it('still tracks the Python package', () => {
    expect(isIgnored('waypoint/router.py')).toBe(false);
    expect(isIgnored('waypoint/__init__.py')).toBe(false);
    expect(isIgnored('waypoint/providers.py')).toBe(false);
  });

  it('still tracks every test suite', () => {
    expect(isIgnored('tests/test_router.py')).toBe(false);
    expect(isIgnored('packages/core/test/router.test.ts')).toBe(false);
    expect(isIgnored('apps/desktop/test/desktop.test.ts')).toBe(false);
  });

  it('still tracks the project documentation', () => {
    expect(isIgnored('LICENSE')).toBe(false);
    expect(isIgnored('README.md')).toBe(false);
    expect(isIgnored('SECURITY.md')).toBe(false);
    expect(isIgnored('config.example.yaml')).toBe(false);
  });

  it('still tracks CI workflows', () => {
    expect(isIgnored('.github/workflows/ci.yml')).toBe(false);
  });
});

describe('a fresh clone can build', () => {
  it('rebuilds the renderer bundle when it is absent', async () => {
    const { readFileSync } = await import('node:fs');
    const desktop = JSON.parse(
      readFileSync(join(REPO, 'apps', 'desktop', 'package.json'), 'utf8'),
    ) as { scripts: Record<string, string> };
    expect(desktop.scripts['build:renderer']).toContain('esbuild');
  });

  it('declares the shared packages as workspaces', async () => {
    const { readFileSync } = await import('node:fs');
    const root = JSON.parse(readFileSync(join(REPO, 'package.json'), 'utf8')) as {
      workspaces: string[];
    };
    expect(root.workspaces).toContain('packages/*');
    expect(root.workspaces).toContain('apps/*');
  });

  it('ships no secrets in tracked files', async () => {
    const { readFileSync } = await import('node:fs');
    // The token pattern is the concrete risk here.
    for (const file of ['README.md', 'SECURITY.md', 'config.example.yaml']) {
      const text = readFileSync(join(REPO, file), 'utf8');
      expect(text).not.toMatch(/ghp_[A-Za-z0-9]{20,}/);
      expect(text).not.toMatch(/github_pat_[A-Za-z0-9_]{20,}/);
    }
  });
});